#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# SPDX-License-Identifier: Apache-2.0
# Copyright 2022 Stéphane Caron

"""List of all robot descriptions and their metadata."""

from dataclasses import dataclass
from enum import IntEnum
from typing import AbstractSet, Dict


class Format(IntEnum):
    """Format of a robot description."""

    URDF = 0
    MJCF = 1


@dataclass(frozen=True)
class Description:
    """Metadata for a robot description."""

    formats: AbstractSet[Format]
    tags: AbstractSet[str]
    robot: str
    maker: str | None = None
    dof: int | None = None
    repository: str | None = None
    license_spdx: str | None = None
    license_file: str | None = None

    def __post_init__(self) -> None:
        """Freeze mutable set literals passed to the constructor."""
        object.__setattr__(self, "formats", frozenset(self.formats))
        object.__setattr__(self, "tags", frozenset(self.tags))

    @property
    def has_mjcf(self) -> bool:
        """Check if description provides MJCF."""
        return Format.MJCF in self.formats

    @property
    def has_urdf(self) -> bool:
        """Check if description provides URDF."""
        return Format.URDF in self.formats


DESCRIPTIONS: Dict[str, Description] = {
    "a1_description": Description(
        formats={Format.URDF},
        tags={"quadruped"},
        robot="A1",
        maker="UNITREE Robotics",
        dof=12,
        repository="unitree_ros",
    ),
    "a1_mj_description": Description(
        formats={Format.MJCF},
        tags={"quadruped"},
        robot="A1",
        maker="UNITREE Robotics",
        dof=12,
        repository="unitree_mujoco",
    ),
    "ability_hand_description": Description(
        formats={Format.URDF},
        tags={"end_effector"},
        robot="Ability Hand",
        maker="PSYONIC, Inc.",
        repository="ability-hand-api",
        license_spdx="MIT",
        license_file="LICENSE",
    ),
    "ability_hand_mj_description": Description(
        formats={Format.MJCF},
        tags={"end_effector"},
        robot="Ability Hand",
        maker="PSYONIC, Inc.",
        repository="ability-hand-api",
        license_spdx="MIT",
        license_file="LICENSE",
    ),
    "adam_lite_mj_description": Description(
        formats={Format.MJCF},
        tags={"humanoid"},
        robot="Adam Lite",
        maker="PNDBotics",
        repository="mujoco_menagerie",
        license_spdx="MIT",
    ),
    "aero_hand_open_description": Description(
        formats={Format.URDF},
        tags={"end_effector"},
        robot="Aero Hand Open",
        maker="TetherIA",
        repository="aero-hand-open",
        license_spdx="Apache-2.0",
    ),
    "aero_hand_open_mj_description": Description(
        formats={Format.MJCF},
        tags={"end_effector"},
        robot="Aero Hand Open",
        maker="TetherIA",
        repository="mujoco_menagerie",
        license_spdx="Apache-2.0",
    ),
    "aliengo_description": Description(
        formats={Format.URDF},
        tags={"quadruped"},
        robot="Aliengo",
        maker="UNITREE Robotics",
        dof=12,
        repository="unitree_ros",
    ),
    "aliengo_mj_description": Description(
        formats={Format.MJCF},
        tags={"quadruped"},
        robot="Aliengo",
        maker="UNITREE Robotics",
        dof=12,
        repository="unitree_mujoco",
    ),
    "allegro_hand_description": Description(
        formats={Format.URDF},
        tags={"end_effector"},
        robot="Allegro Hand",
        maker="Wonik Robotics",
        repository="drake",
        license_spdx="BSD",
    ),
    "allegro_hand_mj_description": Description(
        formats={Format.MJCF},
        tags={"end_effector"},
        robot="Allegro Hand",
        maker="Wonik Robotics",
        repository="mujoco_menagerie",
        license_spdx="BSD-2-Clause",
    ),
    "aloha_mj_description": Description(
        formats={Format.MJCF},
        tags={"dual_arm"},
        robot="Aloha 2",
        maker="Trossen Robotics",
        dof=14,
        repository="mujoco_menagerie",
    ),
    "anymal_b_description": Description(
        formats={Format.URDF},
        tags={"quadruped"},
        robot="ANYmal B",
        maker="ANYbotics",
        dof=12,
        repository="anymal_b_simple_description",
    ),
    "anymal_b_mj_description": Description(
        formats={Format.MJCF},
        tags={"quadruped"},
        robot="ANYmal B",
        maker="ANYbotics",
        dof=12,
        repository="mujoco_menagerie",
    ),
    "anymal_c_description": Description(
        formats={Format.URDF},
        tags={"quadruped"},
        robot="ANYmal C",
        maker="ANYbotics",
        dof=12,
        repository="anymal_c_simple_description",
    ),
    "anymal_c_mj_description": Description(
        formats={Format.MJCF},
        tags={"quadruped"},
        robot="ANYmal C",
        maker="ANYbotics",
        dof=12,
        repository="mujoco_menagerie",
    ),
    "anymal_d_description": Description(
        formats={Format.URDF},
        tags={"quadruped"},
        robot="ANYmal D",
        maker="ANYbotics",
        dof=12,
        repository="anymal_d_simple_description",
    ),
    "apollo_mj_description": Description(
        formats={Format.MJCF},
        tags={"humanoid"},
        robot="Apollo",
        maker="Apptronik",
        repository="mujoco_menagerie",
        license_spdx="Apache-2.0",
    ),
    "arx_l5_mj_description": Description(
        formats={Format.MJCF},
        tags={"arm"},
        robot="L5",
        maker="ARX",
        repository="mujoco_menagerie",
        license_spdx="BSD-3-Clause",
    ),
    "atlas_drc_description": Description(
        formats={Format.URDF},
        tags={"humanoid"},
        robot="Atlas DRC (v3)",
        maker="Boston Dynamics",
        repository="drake",
        license_spdx="BSD-3-Clause",
    ),
    "atlas_v4_description": Description(
        formats={Format.URDF},
        tags={"humanoid"},
        robot="Atlas v4",
        maker="Boston Dynamics",
        repository="roboschool",
        license_spdx="MIT",
    ),
    "b1_description": Description(
        formats={Format.URDF},
        tags={"quadruped"},
        robot="B1",
        maker="UNITREE Robotics",
        dof=12,
        repository="unitree_ros",
    ),
    "b2_description": Description(
        formats={Format.URDF},
        tags={"quadruped"},
        robot="B2",
        maker="UNITREE Robotics",
        dof=12,
        repository="unitree_ros",
    ),
    "bambot_description": Description(
        formats={Format.URDF},
        tags={"mobile_manipulator"},
        robot="BamBot",
        maker="Tim Qian",
        repository="bambot",
        license_spdx="Apache-2.0",
        license_file="LICENSE",
    ),
    "barrett_hand_description": Description(
        formats={Format.URDF},
        tags={"end_effector"},
        robot="BarrettHand",
        maker="Barrett Technology",
        repository="bhand_model",
        license_spdx="BSD",
        license_file="manifest.xml",
    ),
    "baxter_description": Description(
        formats={Format.URDF},
        tags={"dual_arm"},
        robot="Baxter",
        maker="Rethink Robotics",
        dof=15,
        repository="baxter_common",
    ),
    "berkeley_humanoid_description": Description(
        formats={Format.URDF},
        tags={"humanoid"},
        robot="Berkeley Humanoid",
        maker="Hybrid Robotics",
        repository="berkeley_humanoid_description",
        license_spdx="BSD-3-Clause",
    ),
    "bolt_description": Description(
        formats={Format.URDF},
        tags={"biped"},
        robot="Bolt",
        maker="ODRI",
        dof=6,
        repository="example-robot-data",
    ),
    "booster_t1_description": Description(
        formats={Format.URDF},
        tags={"humanoid"},
        robot="Booster T1",
        maker="Booster Robotics",
        repository="booster_gym",
        license_spdx="Apache-2.0",
        license_file="LICENSE",
    ),
    "booster_t1_mj_description": Description(
        formats={Format.MJCF},
        tags={"humanoid"},
        robot="Booster T1",
        maker="Booster Robotics",
        repository="mujoco_menagerie",
        license_spdx="Apache-2.0",
    ),
    "cassie_description": Description(
        formats={Format.URDF},
        tags={"biped"},
        robot="Cassie",
        maker="Agility Robotics",
        dof=16,
        repository="cassie_description",
    ),
    "cassie_mj_description": Description(
        formats={Format.MJCF},
        tags={"biped"},
        robot="Cassie",
        maker="Agility Robotics",
        dof=16,
        repository="mujoco_menagerie",
    ),
    "cf2_description": Description(
        formats={Format.URDF},
        tags={"drone"},
        robot="Crazyflie 2.0",
        maker="Bitcraze",
        dof=0,
        repository="gym-pybullet-drones",
    ),
    "cf2_mj_description": Description(
        formats={Format.MJCF},
        tags={"drone"},
        robot="Crazyflie 2.0",
        maker="Bitcraze",
        dof=6,
        repository="mujoco_menagerie",
    ),
    "double_pendulum_description": Description(
        formats={Format.URDF},
        tags={"educational"},
        robot="Double Pendulum",
        dof=2,
        repository="example-robot-data",
        license_spdx="BSD-3-Clause",
    ),
    "draco3_description": Description(
        formats={Format.URDF},
        tags={"humanoid"},
        robot="Draco3",
        maker="Apptronik",
        repository="draco3_description",
        license_spdx="BSD-2-Clause",
    ),
    "dynamixel_2r_mj_description": Description(
        formats={Format.MJCF},
        tags={"educational"},
        robot="Dynamixel 2R",
        dof=2,
        repository="mujoco_menagerie",
        license_spdx="MIT",
    ),
    "edo_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="e.DO",
        maker="Comau",
        repository="eDO_description",
        license_spdx="BSD-3-Clause",
        license_file="LICENSE",
    ),
    "elf2_description": Description(
        formats={Format.URDF},
        tags={"humanoid"},
        robot="Elf2",
        maker="BXI Robotics",
        repository="bxi_robot_models",
        license_spdx="Apache-2.0",
        license_file="LICENSE",
    ),
    "elf2_mj_description": Description(
        formats={Format.MJCF},
        tags={"humanoid"},
        robot="Elf2",
        maker="BXI Robotics",
        repository="bxi_robot_models",
        license_spdx="Apache-2.0",
        license_file="LICENSE",
    ),
    "ergocub_description": Description(
        formats={Format.URDF},
        tags={"humanoid"},
        robot="ergoCub",
        maker="IIT",
        repository="ergocub-software",
        license_spdx="BSD-3-Clause",
    ),
    "eve_r3_description": Description(
        formats={Format.URDF},
        tags={"mobile_manipulator"},
        robot="Eve R3",
        maker="Halodi",
        repository="halodi-robot-models",
        license_spdx="Apache-2.0",
    ),
    "fanuc_m710ic_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="M-710iC",
        maker="Fanuc",
        repository="fanuc_m710ic_description",
        license_spdx="BSD-3-Clause",
    ),
    "fer_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="FER",
        maker="Franka Robotics",
        repository="franka_description",
        license_spdx="Apache-2.0",
    ),
    "fetch_description": Description(
        formats={Format.URDF},
        tags={"mobile_manipulator"},
        robot="Fetch",
        maker="Fetch Robotics",
        repository="roboschool",
        license_spdx="MIT",
    ),
    "finger_edu_description": Description(
        formats={Format.URDF},
        tags={"educational"},
        robot="FingerEdu",
        dof=3,
        repository="example-robot-data",
        license_spdx="BSD-3-Clause",
    ),
    "fr3_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="FR3",
        maker="Franka Robotics",
        repository="franka_description",
        license_spdx="Apache-2.0",
    ),
    "fr3_mj_description": Description(
        formats={Format.MJCF},
        tags={"arm"},
        robot="FR3",
        maker="Franka Robotics",
        repository="mujoco_menagerie",
        license_spdx="Apache-2.0",
    ),
    "fr3_v2_1_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="FR3 v2.1",
        maker="Franka Robotics",
        repository="franka_description",
        license_spdx="Apache-2.0",
    ),
    "fr3_v2_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="FR3 v2",
        maker="Franka Robotics",
        repository="franka_description",
        license_spdx="Apache-2.0",
    ),
    "fr3_v2_mj_description": Description(
        formats={Format.MJCF},
        tags={"arm"},
        robot="FR3 v2",
        maker="Franka Robotics",
        repository="mujoco_menagerie",
        license_spdx="Apache-2.0",
    ),
    "g1_description": Description(
        formats={Format.URDF},
        tags={"humanoid"},
        robot="G1",
        maker="UNITREE Robotics",
        repository="unitree_ros",
        license_spdx="BSD-3-Clause",
    ),
    "g1_mj_description": Description(
        formats={Format.MJCF},
        tags={"humanoid"},
        robot="G1",
        maker="UNITREE Robotics",
        repository="mujoco_menagerie",
        license_spdx="BSD-3-Clause",
    ),
    "gen2_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="Gen2",
        maker="Kinova",
        repository="example-robot-data",
        license_spdx="BSD-3-Clause",
    ),
    "gen3_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="Gen3",
        maker="Kinova",
        repository="ros2_kortex",
        license_spdx="BSD-3-Clause",
    ),
    "gen3_lite_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="Gen3 Lite",
        maker="Kinova",
        repository="ros2_kortex",
        license_spdx="BSD-3-Clause",
    ),
    "gen3_mj_description": Description(
        formats={Format.MJCF},
        tags={"arm"},
        robot="Gen3",
        maker="Kinova",
        repository="mujoco_menagerie",
        license_spdx="BSD-2-Clause",
    ),
    "ginger_description": Description(
        formats={Format.URDF},
        tags={"mobile_manipulator"},
        robot="Ginger",
        maker="Paaila Technology",
        repository="GingerURDF",
        license_spdx="BSD",
    ),
    "go1_description": Description(
        formats={Format.URDF},
        tags={"quadruped"},
        robot="Go1",
        maker="UNITREE Robotics",
        dof=12,
        repository="unitree_ros",
    ),
    "go1_mj_description": Description(
        formats={Format.MJCF},
        tags={"quadruped"},
        robot="Go1",
        maker="UNITREE Robotics",
        dof=12,
        repository="mujoco_menagerie",
    ),
    "go2_description": Description(
        formats={Format.URDF},
        tags={"quadruped"},
        robot="Go2",
        maker="UNITREE Robotics",
        dof=12,
        repository="unitree_ros",
    ),
    "go2_mj_description": Description(
        formats={Format.MJCF},
        tags={"quadruped"},
        robot="Go2",
        maker="UNITREE Robotics",
        dof=12,
        repository="mujoco_menagerie",
    ),
    "gr1_description": Description(
        formats={Format.URDF},
        tags={"humanoid"},
        robot="GR-1",
        maker="Fourier",
        repository="Wiki-GRx-Models",
        license_spdx="GPL-3.0",
        license_file="LICENSE",
    ),
    "h1_2_description": Description(
        formats={Format.URDF},
        tags={"humanoid"},
        robot="H1_2",
        maker="UNITREE Robotics",
        repository="unitree_ros",
        license_spdx="BSD-3-Clause",
    ),
    "h1_2_mj_description": Description(
        formats={Format.MJCF},
        tags={"humanoid"},
        robot="H1_2",
        maker="UNITREE Robotics",
        repository="unitree_ros",
        license_spdx="BSD-3-Clause",
    ),
    "h1_description": Description(
        formats={Format.URDF},
        tags={"humanoid"},
        robot="H1",
        maker="UNITREE Robotics",
        repository="unitree_ros",
        license_spdx="BSD-3-Clause",
    ),
    "h1_mj_description": Description(
        formats={Format.MJCF},
        tags={"humanoid"},
        robot="H1",
        maker="UNITREE Robotics",
        repository="mujoco_menagerie",
        license_spdx="BSD-3-Clause",
    ),
    "hyq_description": Description(
        formats={Format.URDF},
        tags={"quadruped"},
        robot="HyQ",
        maker="IIT",
        dof=12,
        repository="example-robot-data",
    ),
    "icub_description": Description(
        formats={Format.URDF},
        tags={"humanoid"},
        robot="iCub",
        maker="IIT",
        repository="icub-models",
        license_spdx="CC-BY-SA-4.0 ✖️",
    ),
    "iiwa14_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="iiwa 14",
        maker="KUKA",
        repository="drake",
        license_spdx="BSD-3-Clause",
    ),
    "iiwa14_mj_description": Description(
        formats={Format.MJCF},
        tags={"arm"},
        robot="iiwa 14",
        maker="KUKA",
        repository="mujoco_menagerie",
        license_spdx="BSD-3-Clause",
    ),
    "iiwa7_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="iiwa 7",
        maker="KUKA",
        repository="differentiable-robot-model",
        license_spdx="MIT",
    ),
    "j2n4s300_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="Jaco2 j2n4s300",
        maker="Kinova",
        repository="kinova-ros",
        license_spdx="BSD-3-Clause",
    ),
    "j2n6s200_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="Jaco2 j2n6s200",
        maker="Kinova",
        repository="kinova-ros",
        license_spdx="BSD-3-Clause",
    ),
    "j2n6s300_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="Jaco2 j2n6s300",
        maker="Kinova",
        repository="kinova-ros",
        license_spdx="BSD-3-Clause",
    ),
    "j2n7s300_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="Jaco2 j2n7s300",
        maker="Kinova",
        repository="kinova-ros",
        license_spdx="BSD-3-Clause",
    ),
    "j2s6s200_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="Jaco2 j2s6s200",
        maker="Kinova",
        repository="kinova-ros",
        license_spdx="BSD-3-Clause",
    ),
    "j2s6s300_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="Jaco2 j2s6s300",
        maker="Kinova",
        repository="kinova-ros",
        license_spdx="BSD-3-Clause",
    ),
    "j2s7s300_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="Jaco2 j2s7s300",
        maker="Kinova",
        repository="kinova-ros",
        license_spdx="BSD-3-Clause",
    ),
    "jaxon_description": Description(
        formats={Format.URDF},
        tags={"humanoid"},
        robot="JAXON",
        maker="JSK",
        repository="jaxon_description",
        license_spdx="CC-BY-SA-4.0 ✖️",
    ),
    "jvrc_description": Description(
        formats={Format.URDF},
        tags={"humanoid"},
        robot="JVRC-1",
        maker="AIST",
        repository="jvrc_description",
        license_spdx="BSD-2-Clause",
    ),
    "jvrc_mj_description": Description(
        formats={Format.MJCF},
        tags={"humanoid"},
        robot="JVRC-1",
        maker="AIST",
        repository="jvrc_mj_description",
        license_spdx="BSD-2-Clause",
    ),
    "laikago_description": Description(
        formats={Format.URDF},
        tags={"quadruped"},
        robot="Laikago",
        maker="UNITREE Robotics",
        dof=12,
        repository="unitree_mujoco",
    ),
    "leap_hand_mj_description": Description(
        formats={Format.MJCF},
        tags={"end_effector"},
        robot="LEAP Hand",
        maker="Carnegie Mellon University",
        repository="mujoco_menagerie",
        license_spdx="MIT",
    ),
    "leap_hand_v1_description": Description(
        formats={Format.URDF},
        tags={"end_effector"},
        robot="LEAP Hand v1",
        maker="Carnegie Mellon University",
        repository="LEAP_Hand_Sim",
        license_spdx="MIT",
    ),
    "low_cost_robot_arm_mj_description": Description(
        formats={Format.MJCF},
        tags={"arm"},
        robot="Low-cost robot arm",
        maker="Alexander Koch",
        repository="mujoco_menagerie",
        license_spdx="Apache-2.0",
    ),
    "mini_cheetah_description": Description(
        formats={Format.URDF},
        tags={"quadruped"},
        robot="Mini Cheetah",
        maker="MIT",
        dof=12,
        repository="mini_cheetah_urdf",
    ),
    "minitaur_description": Description(
        formats={Format.URDF},
        tags={"quadruped"},
        robot="Minitaur",
        maker="Ghost Robotics",
        dof=16,
        repository="bullet3",
    ),
    "mujoco_humanoid_mj_description": Description(
        formats={Format.MJCF},
        tags={"educational", "humanoid"},
        robot="MuJoCo Humanoid",
        dof=27,
        repository="mujoco",
        license_spdx="Apache-2.0",
        license_file="LICENSE",
    ),
    "n1_description": Description(
        formats={Format.URDF},
        tags={"humanoid"},
        robot="N1",
        maker="Fourier",
        repository="Wiki-GRx-Models-FourierN1",
        license_spdx="Apache-2.0",
        license_file="LICENSE",
    ),
    "n1_mj_description": Description(
        formats={Format.MJCF},
        tags={"humanoid"},
        robot="N1",
        maker="Fourier",
        repository="mujoco_menagerie",
        license_spdx="Apache-2.0",
    ),
    "nextage_description": Description(
        formats={Format.URDF},
        tags={"dual_arm"},
        robot="NEXTAGE",
        maker="Kawada Robotics",
        dof=15,
        repository="rtmros_nextage",
    ),
    "omx_f_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="OMX-F",
        maker="ROBOTIS",
        repository="open_manipulator",
        license_spdx="Apache-2.0",
    ),
    "omx_l_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="OMX-L",
        maker="ROBOTIS",
        repository="open_manipulator",
        license_spdx="Apache-2.0",
    ),
    "omy_3m_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="OMY-3M",
        maker="ROBOTIS",
        repository="open_manipulator",
        license_spdx="Apache-2.0",
    ),
    "omy_f3m_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="OMY-F3M",
        maker="ROBOTIS",
        repository="open_manipulator",
        license_spdx="Apache-2.0",
    ),
    "omy_l100_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="OMY-L100",
        maker="ROBOTIS",
        repository="open_manipulator",
        license_spdx="Apache-2.0",
    ),
    "op3_mj_description": Description(
        formats={Format.MJCF},
        tags={"humanoid"},
        robot="OP3",
        maker="ROBOTIS",
        repository="mujoco_menagerie",
        license_spdx="Apache-2.0",
    ),
    "open_manipulator_x_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="OpenMANIPULATOR-X",
        maker="ROBOTIS",
        repository="open_manipulator",
        license_spdx="Apache-2.0",
    ),
    "openarm_v1_mj_description": Description(
        formats={Format.MJCF},
        tags={"dual_arm"},
        robot="OpenArm",
        maker="Enactic",
        dof=16,
        repository="openarm_mujoco",
    ),
    "panda_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="Panda",
        maker="Franka Robotics",
        repository="example-robot-data",
        license_spdx="Apache-2.0",
    ),
    "panda_mj_description": Description(
        formats={Format.MJCF},
        tags={"arm"},
        robot="Panda",
        maker="Franka Robotics",
        repository="mujoco_menagerie",
        license_spdx="Apache-2.0",
    ),
    "pepper_description": Description(
        formats={Format.URDF},
        tags={"mobile_manipulator"},
        robot="Pepper",
        maker="SoftBank Robotics",
        repository="pepper_description",
        license_spdx="BSD-2-Clause",
    ),
    "piper_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="PiPER",
        maker="AgileX",
        repository="Piper_ros",
        license_spdx="MIT",
    ),
    "piper_mj_description": Description(
        formats={Format.MJCF},
        tags={"arm"},
        robot="PiPER",
        maker="AgileX",
        repository="mujoco_menagerie",
        license_spdx="MIT",
    ),
    "poppy_ergo_jr_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="Poppy Ergo Jr",
        maker="Poppy Project",
        repository="poppy_ergo_jr_description",
        license_spdx="GPL-3.0",
    ),
    "poppy_torso_description": Description(
        formats={Format.URDF},
        tags={"dual_arm"},
        robot="Poppy Torso",
        maker="Poppy Project",
        dof=13,
        repository="poppy_torso_description",
    ),
    "pr2_description": Description(
        formats={Format.URDF},
        tags={"dual_arm", "mobile_manipulator"},
        robot="PR2",
        maker="Willow Garage",
        repository="robot-assets",
        license_spdx="BSD",
    ),
    "r2_description": Description(
        formats={Format.URDF},
        tags={"humanoid"},
        robot="Robonaut 2",
        maker="NASA JSC Robotics",
        repository="nasa-urdf-robots",
        license_spdx="NASA-1.3",
    ),
    "rby1_description": Description(
        formats={Format.URDF},
        tags={"mobile_manipulator"},
        robot="RBY1",
        maker="Rainbow Robotics",
        repository="rby1_description",
        license_spdx="MIT",
        license_file="LICENSE",
    ),
    "reachy_description": Description(
        formats={Format.URDF},
        tags={"mobile_manipulator"},
        robot="Reachy",
        maker="Pollen Robotics",
        repository="reachy_description",
        license_spdx="Apache-2.0",
    ),
    "rhea_description": Description(
        formats={Format.URDF},
        tags={"biped"},
        robot="Rhea",
        maker="Gabrael Levine",
        dof=7,
        repository="rhea_description",
    ),
    "rizon4_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="Rizon4",
        maker="Flexiv Robotics",
        repository="flexiv_description",
        license_spdx="Apache-2.0",
    ),
    "rizon4_mj_description": Description(
        formats={Format.MJCF},
        tags={"arm"},
        robot="Rizon4",
        maker="Flexiv Robotics",
        repository="mujoco_menagerie",
        license_spdx="Apache-2.0",
        license_file="LICENSE",
    ),
    "robotiq_2f85_description": Description(
        formats={Format.URDF},
        tags={"end_effector"},
        robot="Robotiq 2F-85",
        maker="Robotiq",
        repository="robotiq_arg85_description",
        license_spdx="BSD-2-Clause",
    ),
    "robotiq_2f85_mj_description": Description(
        formats={Format.MJCF},
        tags={"end_effector"},
        robot="Robotiq 2F-85",
        maker="Robotiq",
        repository="mujoco_menagerie",
        license_spdx="BSD-2-Clause",
    ),
    "robotiq_2f85_v4_description": Description(
        formats={Format.URDF},
        tags={"end_effector"},
        robot="Robotiq 2F-85 v4",
        maker="Robotiq",
        repository="robotiq_2f_85",
        license_spdx="BSD-2-Clause",
    ),
    "robotiq_2f85_v4_mj_description": Description(
        formats={Format.MJCF},
        tags={"end_effector"},
        robot="Robotiq 2F-85",
        maker="Robotiq",
        repository="mujoco_menagerie",
        license_spdx="BSD-2-Clause",
    ),
    "romeo_description": Description(
        formats={Format.URDF},
        tags={"humanoid"},
        robot="Romeo",
        maker="Aldebaran Robotics",
        repository="romeo_robot",
        license_spdx="BSD-3-Clause",
    ),
    "rsk_description": Description(
        formats={Format.URDF},
        tags={"wheeled"},
        robot="RSK Omnidirectional",
        maker="Robot Soccer Kit",
        repository="onshape-to-robot-examples",
        license_spdx="MIT",
    ),
    "rsk_mj_description": Description(
        formats={Format.MJCF},
        tags={"wheeled"},
        robot="RSK Omnidirectional",
        maker="Robot Soccer Kit",
        repository="mujoco_menagerie",
        license_spdx="MIT",
    ),
    "sawyer_mj_description": Description(
        formats={Format.MJCF},
        tags={"arm"},
        robot="Sawyer",
        maker="Rethink Robotics",
        repository="mujoco_menagerie",
        license_spdx="Apache-2.0",
    ),
    "shadow_dexee_mj_description": Description(
        formats={Format.MJCF},
        tags={"end_effector"},
        robot="Shadow DEX-EE",
        maker="The Shadow Robot Company",
        repository="mujoco_menagerie",
        license_spdx="Apache-2.0",
    ),
    "shadow_hand_mj_description": Description(
        formats={Format.MJCF},
        tags={"end_effector"},
        robot="Shadow Hand",
        maker="The Shadow Robot Company",
        repository="mujoco_menagerie",
        license_spdx="Apache-2.0",
    ),
    "sigmaban_description": Description(
        formats={Format.URDF},
        tags={"humanoid"},
        robot="SigmaBan",
        maker="Rhoban",
        repository="sigmaban_urdf",
        license_spdx="MIT",
    ),
    "simple_humanoid_description": Description(
        formats={Format.URDF},
        tags={"educational", "humanoid"},
        robot="Simple Humanoid",
        dof=29,
        repository="simple_humanoid_description",
        license_spdx="BSD-2-Clause",
    ),
    "skydio_x2_description": Description(
        formats={Format.URDF},
        tags={"drone"},
        robot="Skydio X2",
        maker="Skydio",
        dof=6,
        repository="skydio_x2_description",
    ),
    "skydio_x2_mj_description": Description(
        formats={Format.MJCF},
        tags={"drone"},
        robot="Skydio X2",
        maker="Skydio",
        dof=6,
        repository="mujoco_menagerie",
    ),
    "so_arm100_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="SO-ARM100",
        maker="The Robot Studio",
        repository="SO-ARM100",
        license_spdx="Apache-2.0",
    ),
    "so_arm100_mj_description": Description(
        formats={Format.MJCF},
        tags={"arm"},
        robot="SO-ARM100",
        maker="The Robot Studio",
        repository="mujoco_menagerie",
        license_spdx="Apache-2.0",
    ),
    "so_arm101_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="SO-ARM101",
        maker="The Robot Studio",
        repository="SO-ARM100",
        license_spdx="Apache-2.0",
    ),
    "so_arm101_mj_description": Description(
        formats={Format.MJCF},
        tags={"arm"},
        robot="SO-ARM101",
        maker="The Robot Studio",
        repository="SO-ARM100",
        license_spdx="Apache-2.0",
    ),
    "solo_description": Description(
        formats={Format.URDF},
        tags={"quadruped"},
        robot="Solo",
        maker="ODRI",
        dof=12,
        repository="example-robot-data",
    ),
    "spot_mj_description": Description(
        formats={Format.MJCF},
        tags={"quadruped"},
        robot="Spot",
        maker="Boston Dynamics",
        dof=12,
        repository="mujoco_menagerie",
    ),
    "spryped_description": Description(
        formats={Format.URDF},
        tags={"biped"},
        robot="Spryped",
        maker="Benjamin Bokser",
        dof=8,
        repository="spryped",
    ),
    "stretch_3_mj_description": Description(
        formats={Format.MJCF},
        tags={"mobile_manipulator"},
        robot="Stretch 3",
        maker="Hello Robot",
        repository="mujoco_menagerie",
        license_spdx="Apache-2.0",
    ),
    "stretch_description": Description(
        formats={Format.URDF},
        tags={"mobile_manipulator"},
        robot="Stretch RE1",
        maker="Hello Robot",
        repository="stretch_description",
        license_spdx="CC-BY-SA-4.0 ✖️",
    ),
    "stretch_mj_description": Description(
        formats={Format.MJCF},
        tags={"mobile_manipulator"},
        robot="Stretch 2",
        maker="Hello Robot",
        repository="mujoco_menagerie",
        license_spdx="Clear BSD",
    ),
    "stretch_se3_description": Description(
        formats={Format.URDF},
        tags={"mobile_manipulator"},
        robot="Stretch SE3",
        maker="Hello Robot",
        repository="stretch_urdf",
        license_spdx="Clear BSD",
    ),
    "talos_description": Description(
        formats={Format.URDF},
        tags={"humanoid"},
        robot="TALOS",
        maker="PAL Robotics",
        repository="talos-data",
        license_spdx="Apache-2.0",
    ),
    "talos_mj_description": Description(
        formats={Format.MJCF},
        tags={"humanoid"},
        robot="TALOS",
        maker="PAL Robotics",
        repository="mujoco_menagerie",
        license_spdx="Apache-2.0",
    ),
    "tiago++_mj_description": Description(
        formats={Format.MJCF},
        tags={"mobile_manipulator"},
        robot="TIAGo++",
        maker="PAL Robotics",
        repository="mujoco_menagerie",
        license_spdx="Apache-2.0",
    ),
    "tiago_description": Description(
        formats={Format.URDF},
        tags={"mobile_manipulator"},
        robot="TIAGo",
        maker="PAL Robotics",
        repository="example-robot-data",
        license_spdx="Apache-2.0",
    ),
    "toddlerbot_2xc_mj_description": Description(
        formats={Format.MJCF},
        tags={"humanoid"},
        robot="ToddlerBot 2XC",
        maker="Stanford University",
        repository="mujoco_menagerie",
        license_spdx="MIT",
    ),
    "toddlerbot_2xm_mj_description": Description(
        formats={Format.MJCF},
        tags={"humanoid"},
        robot="ToddlerBot 2XM",
        maker="Stanford University",
        repository="mujoco_menagerie",
        license_spdx="MIT",
    ),
    "toddlerbot_description": Description(
        formats={Format.URDF},
        tags={"humanoid"},
        robot="ToddlerBot",
        maker="Stanford University",
        repository="toddlerbot",
        license_spdx="MIT",
    ),
    "trifinger_edu_description": Description(
        formats={Format.URDF},
        tags={"educational"},
        robot="TriFingerEdu",
        dof=9,
        repository="differentiable-robot-model",
        license_spdx="MIT",
    ),
    "upkie_description": Description(
        formats={Format.URDF},
        tags={"biped", "wheeled"},
        robot="Upkie",
        maker="Tast's Robots",
        dof=6,
        repository="upkie_description",
    ),
    "ur10_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="UR10",
        maker="Universal Robots",
        repository="example-robot-data",
        license_spdx="Apache-2.0",
    ),
    "ur10_official_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="UR10 (official)",
        maker="Universal Robots",
        repository="Universal_Robots_ROS2_Description",
        license_spdx="BSD-3-Clause",
    ),
    "ur10e_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="UR10e",
        maker="Universal Robots",
        repository="Universal_Robots_ROS2_Description",
        license_spdx="BSD-3-Clause",
    ),
    "ur10e_mj_description": Description(
        formats={Format.MJCF},
        tags={"arm"},
        robot="UR10e",
        maker="Universal Robots",
        repository="mujoco_menagerie",
        license_spdx="BSD-3-Clause",
    ),
    "ur12e_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="UR12e",
        maker="Universal Robots",
        repository="Universal_Robots_ROS2_Description",
        license_spdx="BSD-3-Clause",
    ),
    "ur15_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="UR15",
        maker="Universal Robots",
        repository="Universal_Robots_ROS2_Description",
        license_spdx="BSD-3-Clause",
    ),
    "ur16e_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="UR16e",
        maker="Universal Robots",
        repository="Universal_Robots_ROS2_Description",
        license_spdx="BSD-3-Clause",
    ),
    "ur18_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="UR18",
        maker="Universal Robots",
        repository="Universal_Robots_ROS2_Description",
        license_spdx="BSD-3-Clause",
    ),
    "ur20_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="UR20",
        maker="Universal Robots",
        repository="Universal_Robots_ROS2_Description",
        license_spdx="BSD-3-Clause",
    ),
    "ur30_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="UR30",
        maker="Universal Robots",
        repository="Universal_Robots_ROS2_Description",
        license_spdx="BSD-3-Clause",
    ),
    "ur3_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="UR3",
        maker="Universal Robots",
        repository="example-robot-data",
        license_spdx="Apache-2.0",
    ),
    "ur3_official_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="UR3 (official)",
        maker="Universal Robots",
        repository="Universal_Robots_ROS2_Description",
        license_spdx="BSD-3-Clause",
    ),
    "ur3e_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="UR3e",
        maker="Universal Robots",
        repository="Universal_Robots_ROS2_Description",
        license_spdx="BSD-3-Clause",
    ),
    "ur5_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="UR5",
        maker="Universal Robots",
        repository="example-robot-data",
        license_spdx="Apache-2.0",
    ),
    "ur5_official_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="UR5 (official)",
        maker="Universal Robots",
        repository="Universal_Robots_ROS2_Description",
        license_spdx="BSD-3-Clause",
    ),
    "ur5e_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="UR5e",
        maker="Universal Robots",
        repository="Universal_Robots_ROS2_Description",
        license_spdx="BSD-3-Clause",
    ),
    "ur5e_mj_description": Description(
        formats={Format.MJCF},
        tags={"arm"},
        robot="UR5e",
        maker="Universal Robots",
        repository="mujoco_menagerie",
        license_spdx="BSD-3-Clause",
    ),
    "ur7e_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="UR7e",
        maker="Universal Robots",
        repository="Universal_Robots_ROS2_Description",
        license_spdx="BSD-3-Clause",
    ),
    "ur8long_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="UR8 Long",
        maker="Universal Robots",
        repository="Universal_Robots_ROS2_Description",
        license_spdx="BSD-3-Clause",
    ),
    "valkyrie_description": Description(
        formats={Format.URDF},
        tags={"humanoid"},
        robot="Valkyrie",
        maker="NASA JSC Robotics",
        repository="nasa-urdf-robots",
        license_spdx="NASA-1.3",
    ),
    "viper_mj_description": Description(
        formats={Format.MJCF},
        tags={"arm"},
        robot="ViperX",
        maker="Trossen Robotics",
        repository="mujoco_menagerie",
        license_spdx="BSD-3-Clause",
    ),
    "widow_mj_description": Description(
        formats={Format.MJCF},
        tags={"arm"},
        robot="WidowX",
        maker="Trossen Robotics",
        repository="mujoco_menagerie",
        license_spdx="BSD-3-Clause",
    ),
    "wl_p311d_description": Description(
        formats={Format.URDF},
        tags={"quadruped", "wheeled"},
        robot="WL P311D",
        maker="LimX Dynamics",
        repository="limxdynamics_robot-description",
        license_spdx="Apache-2.0",
        license_file="LICENSE",
    ),
    "wl_p311e_description": Description(
        formats={Format.URDF},
        tags={"quadruped", "wheeled"},
        robot="WL P311E",
        maker="LimX Dynamics",
        repository="limxdynamics_robot-description",
        license_spdx="Apache-2.0",
        license_file="LICENSE",
    ),
    "xarm6_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="xArm6",
        maker="UFACTORY",
        repository="xarm_ros2",
        license_spdx="BSD-3-Clause",
    ),
    "xarm7_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="xArm7",
        maker="UFACTORY",
        repository="xarm_ros2",
        license_spdx="BSD-3-Clause",
    ),
    "xarm7_mj_description": Description(
        formats={Format.MJCF},
        tags={"arm"},
        robot="xArm7",
        maker="UFACTORY",
        repository="mujoco_menagerie",
        license_spdx="BSD-3-Clause",
    ),
    "yam_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="YAM",
        maker="I2RT Robotics",
        repository="i2rt",
        license_spdx="MIT",
    ),
    "yam_mj_description": Description(
        formats={Format.MJCF},
        tags={"arm"},
        robot="YAM",
        maker="I2RT Robotics",
        repository="mujoco_menagerie",
        license_spdx="MIT",
    ),
    "yumi_description": Description(
        formats={Format.URDF},
        tags={"dual_arm"},
        robot="YuMi",
        maker="ABB",
        dof=16,
        repository="robot-assets",
    ),
    "z1_description": Description(
        formats={Format.URDF},
        tags={"arm"},
        robot="Z1",
        maker="UNITREE Robotics",
        repository="unitree_ros",
        license_spdx="BSD-3-Clause",
    ),
    "z1_mj_description": Description(
        formats={Format.MJCF},
        tags={"arm"},
        robot="Z1",
        maker="UNITREE Robotics",
        repository="mujoco_menagerie",
        license_spdx="BSD-3-Clause",
    ),
}
