name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs:
    coverage:
        name: "Coverage"
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v4

            - name: "Set up pixi"
              uses: prefix-dev/setup-pixi@v0.8.10
              with:
                  pixi-version: v0.72.2
                  environments: coverage
                  locked: true
                  cache: true

            - name: "Check coverage"
              run: pixi run -e coverage coverage

            - name: "Coveralls"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: pixi run -e coverage coveralls --service=github

    lint:
        name: "Code style"
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v4

            - name: "Set up pixi"
              uses: prefix-dev/setup-pixi@v0.8.10
              with:
                  pixi-version: v0.72.2
                  environments: lint
                  locked: true
                  cache: true

            - name: "Check code format"
              run: pixi run -e lint lint

    loader:
        name: "Loader: ${{ matrix.loader }}"
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                loader: ["idyntree", "mujoco", "pinocchio", "pybullet", "robomeshcat", "yourdfpy"]

        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v4

            - name: "Set up pixi"
              uses: prefix-dev/setup-pixi@v0.8.10
              with:
                  pixi-version: v0.72.2
                  environments: loader-${{ matrix.loader }}
                  locked: true
                  cache: true

            - name: "Run loader tests"
              run: pixi run -e loader-${{ matrix.loader }} test-loader-${{ matrix.loader }}

    ci_success:
        name: "CI success"
        runs-on: ubuntu-latest
        needs: [coverage, lint, loader]
        steps:
            - run: echo "CI workflow completed successfully"
